import logging
import asyncio
import streamlit as st
from cachetools import TTLCache, cached
from app_components import (
    tag_filter_component,
    posts_component,
    format_user_input,
    get_all_tags,
)
from data_loader import Post, download_posts, load_posts
from gpt import tag, batch_user_tag

st.set_page_config(page_title="UW News tagging", page_icon="📰", layout="wide")

# Initialize session state
if "filter_selection" not in st.session_state:
    st.session_state.filter_selection = []

for var in ["user_tags", "user_input", "posts"]:
    if var not in st.session_state:
        st.session_state[var] = None


@cached(cache=TTLCache(maxsize=1, ttl=60))
def get_posts() -> list[Post]:
    """Update and get all posts."""

    existing_posts = load_posts()
    live_posts = download_posts()
    exist_ids = [p.id for p in existing_posts]

    # Filter out posts that are already exist
    new_posts = [post for post in live_posts if post.id not in exist_ids]

    # Tag and save new posts
    for post in new_posts:
        logging.info(f"Tagging new post {post.id}")
        post.tags_gpt = tag(post.title, post.content)
        post.save()

    existing_posts.extend(new_posts)
    return existing_posts


async def async_get_user_tags(posts: list[Post], user_tags: list[str]) -> list[Post]:
    titles = [post.title for post in posts]
    contents = [post.content for post in posts]
    news_user_tags = await batch_user_tag(titles, contents, user_tags)
    for post, tags in zip(posts, news_user_tags):
        post.tags_user = tags
    return posts


@st.cache_data
def get_user_tags(_posts: list[Post], user_tags: list[str]) -> list[Post]:
    """Append user tags to posts."""

    return asyncio.run(async_get_user_tags(_posts, user_tags))


main_screen = st.container()


def run() -> None:
    """Run the data pipeline."""

    st.session_state.posts = get_posts()
    st.session_state.user_tags = format_user_input(st.session_state.user_input)

    # Process user tags
    if st.session_state.user_tags:
        st.session_state.posts = get_user_tags(
            st.session_state.posts, st.session_state.user_tags
        )


# Sidebar
with st.sidebar:
    st.subheader("🏷️ User defined tags")
    st.write(
        "You can choose to provide a list of custom tags to change the way the system categorizes news."
    )
    st.session_state.user_input = st.text_input(
        "Optionally enter a list of custom tags (comma separated)",
        key="custom_tags",
        placeholder="e.g. physics, astronomy, space, psychology",
    )

    if st.button("Run"):
        run()


# Splash screen
def splash_screen():
    st.title("UW News tagging (prototype)")

    """
    This demo compares the original tags from UW News articles, 
    sourced from the [news feed](https://news.wisc.edu/feed), 
    with tags that are generated by GPT-4. These newly generated tags are 
    derived from both the title and the complete content of each article.

    [Core prompt engineering code](https://github.com/UW-Madison-DSI/news-tagging/blob/00d2a7d5f5a95ea80549664040648db5f4743e69/gpt.py#L12C1-L27C6)
    """


with main_screen:
    # If the app has not been run, show the splash screen
    # TODO: change to all tags

    if not st.session_state.posts:
        splash_screen()
    else:
        tags = get_all_tags(st.session_state.posts)

        st.header("📰 UW News articles")

        if st.session_state.user_tags:
            st.write(f"Your custom tags: {st.session_state.user_tags}")

        # Show tag filter component
        tag_filter_component(tags)

        # Show posts component
        posts_component(
            st.session_state.posts, with_user_tag=bool(st.session_state.user_tags)
        )
